version: '2'
services:
    multisic-app:
        image: multisic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://multisic-mysql:3306/multisic?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    multisic-mysql:
        extends:
            file: mysql.yml
            service: multisic-mysql
